--- @class Comment
--- @field id number
--- @field url string
--- @field path string
--- @field line number
--- @field start_line number
--- @field original_line? number
--- @field original_start_line? number
--- @field outdated boolean
--- @field user string
--- @field body string
--- @field updated_at string
--- @field diff_hunk string
--- @field commit_id? string
--- @field original_commit_id? string
--- @field pending boolean held in an unsubmitted review

--- @class GroupedComment
--- @field id number
--- @field line number
--- @field start_line number
--- @field outdated boolean
--- @field url string
--- @field content string
--- @field comments Comment[]
--- @field commit_id? string
--- @field original_commit_id? string
--- @field thread_id? string
--- @field resolved boolean

--- A review that exists on GitHub but has not been submitted yet. Comments added
--- while it is open stay invisible to everyone else until the review is submitted.
--- @class PendingReview
--- @field id number REST review id, used to submit and discard
--- @field node_id string GraphQL review id, used to attach comments
--- @field pr_number number PR the review belongs to

--- @class FileNameAndLinePair
--- @field [1] string filename
--- @field [2] number line

--- @class ChangedFile
--- @field filename string
--- @field status string

--- @class Commit
--- @field oid string
--- @field messageHeadline string
--- @field messageBody string
--- @field authoredDate string
--- @field committedDate string
--- @field authors { login?: string, name?: string, email?: string }[]

--- @class CommitFile
--- @field filename string
--- @field previous_filename? string
--- @field status string
--- @field additions number
--- @field deletions number
--- @field patch? string

--- @class CommitDetails
--- @field sha string
--- @field html_url string
--- @field commit { message: string, author: table, committer: table, verification?: table }
--- @field author? { login: string }
--- @field committer? { login: string }
--- @field parents { sha: string }[]
--- @field stats { additions: number, deletions: number, total: number }
--- @field files CommitFile[]

--- @class PullRequest
--- @field number number
--- @field title? string
--- @field author? { login: string }
--- @field labels? { name: string }[]
--- @field createdAt? string
--- @field isDraft? boolean
--- @field updatedAt? string
--- @field baseRefName string
--- @field baseRefOid string
--- @field headRefName string
--- @field headRefOid string
--- @field reviewDecision string
--- @field statusCheckRollup? StatusCheckRollup[]

--- @class StatusCheckRollup
--- @field __typename? 'CheckRun'|'StatusContext'
--- @field name? string CheckRun name
--- @field context? string legacy commit-status context name
--- @field status? string CheckRun status, e.g. queued, in_progress, completed
--- @field conclusion? string CheckRun conclusion when completed
--- @field state? string legacy commit-status state, e.g. SUCCESS, FAILURE, PENDING
--- @field workflowName? string
--- @field description? string
--- @field detailsUrl? string
--- @field targetUrl? string
